//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CusJo_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserMenu
    {
        public int PrivID { get; set; }
        public int UserID { get; set; }
        public int MenuID { get; set; }
    }
}
